# Generated by Django 3.0.5 on 2020-06-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('selfie', models.CharField(max_length=500)),
                ('npi_score', models.IntegerField(default=0)),
                ('biography', models.CharField(max_length=500)),
                ('media_count', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(verbose_name='created')),
            ],
        ),
    ]
