# Generated by Django 2.2.13 on 2020-06-30 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.BigIntegerField(null=True, verbose_name='post_id')),
                ('posted_on', models.DateTimeField(null=True, verbose_name='posted_on')),
                ('owner', models.CharField(max_length=200, null=True)),
                ('is_comment', models.BooleanField(null=True, verbose_name='is_comment')),
                ('sentiment', models.CharField(max_length=200, null=True, verbose_name='sentiment')),
                ('sscore', models.FloatField(null=True, verbose_name='sscore')),
                ('tag_used', models.BooleanField(default=False, null=True, verbose_name='tag_used')),
                ('likes', models.IntegerField(null=True, verbose_name='likes')),
                ('text', models.TextField(null=True, verbose_name='caption')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.BigIntegerField(null=True, verbose_name='post_id')),
                ('instagram', models.CharField(max_length=200, null=True, verbose_name='instagram')),
                ('posted_on', models.DateTimeField(null=True, verbose_name='posted_on')),
                ('selfie', models.BooleanField(default=False, null=True, verbose_name='selfie')),
                ('person', models.TextField(null=True, verbose_name='person')),
                ('image_path', models.TextField(null=True, verbose_name='image_path')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='user_id')),
                ('instagram', models.CharField(max_length=200, null=True, verbose_name='instagram')),
                ('posted_on', models.DateTimeField(null=True, verbose_name='posted_on')),
                ('post_url', models.TextField(null=True, verbose_name='post_url')),
                ('hashtags', models.TextField(null=True, verbose_name='hashtags')),
                ('mentions', models.TextField(null=True, verbose_name='mentions')),
                ('tagged_users', models.TextField(null=True, verbose_name='tagged_users')),
                ('is_video', models.BooleanField(default=False, null=True, verbose_name='is_video')),
                ('likes', models.BigIntegerField(null=True, verbose_name='likes')),
                ('caption', models.TextField(null=True, verbose_name='caption')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('instagram', models.CharField(max_length=200, null=True)),
                ('selfie', models.CharField(max_length=500, null=True)),
                ('npi_score', models.IntegerField(default=0, null=True)),
                ('biography', models.CharField(max_length=500, null=True)),
                ('media_count', models.IntegerField(default=0, null=True)),
                ('followers', models.IntegerField(default=0, null=True)),
                ('following', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='created')),
                ('state', models.TextField(default='pending', verbose_name='state')),
            ],
        ),
    ]
