# Generated by Django 2.2.12 on 2020-07-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='posted_at',
            field=models.DateField(null=True, verbose_name='posted_at'),
        ),
    ]
