# Generated by Django 2.2.13 on 2020-06-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='biography',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
