# Generated by Django 2.2.12 on 2020-07-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_posts_posted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='posted_at',
        ),
    ]
