# Generated by Django 2.2.13 on 2020-06-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200624_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='selfie',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
