# Generated by Django 2.2.12 on 2020-06-25 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200625_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='caption',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(null=True, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_comment',
            field=models.BooleanField(null=True, verbose_name='is_comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(null=True, verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.BigIntegerField(null=True, verbose_name='post_id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_on',
            field=models.DateTimeField(null=True, verbose_name='posted_on'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(max_length=200, null=True, verbose_name='sentiment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sscore',
            field=models.FloatField(null=True, verbose_name='sscore'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tag_used',
            field=models.BooleanField(default=False, null=True, verbose_name='tag_used'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image_path',
            field=models.TextField(null=True, verbose_name='image_path'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='person',
            field=models.TextField(null=True, verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='post_id',
            field=models.BigIntegerField(null=True, verbose_name='post_id'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='posted_on',
            field=models.DateTimeField(null=True, verbose_name='posted_on'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='selfie',
            field=models.BooleanField(default=False, null=True, verbose_name='selfie'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='caption',
            field=models.TextField(null=True, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='hashtags',
            field=models.TextField(null=True, verbose_name='hashtags'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='instagram',
            field=models.CharField(max_length=200, null=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='is_video',
            field=models.BooleanField(default=False, null=True, verbose_name='is_video'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.BigIntegerField(null=True, verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='mentions',
            field=models.TextField(null=True, verbose_name='mentions'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_url',
            field=models.TextField(null=True, verbose_name='post_url'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='posted_on',
            field=models.DateTimeField(null=True, verbose_name='posted_on'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='tagged_users',
            field=models.TextField(null=True, verbose_name='tagged_users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='biography',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='followers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='following',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='instagram',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='media_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='npi_score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='selfie',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='state',
            field=models.TextField(default='pending', null=True, verbose_name='state'),
        ),
    ]
