# Generated by Django 2.2.13 on 2020-06-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200624_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='selfie',
            field=models.ImageField(upload_to=''),
        ),
    ]
