# Generated by Django 2.2.12 on 2020-07-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_posts_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='private',
            field=models.BooleanField(default=False, verbose_name='isprivate'),
        ),
    ]
