# Generated by Django 3.0.8 on 2020-08-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_users_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='authority',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='entitle',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='exhibit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='exploit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='sufficiency',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='superior',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='vanity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
