# Generated by Django 2.2.12 on 2020-06-25 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200625_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='users',
            name='state',
            field=models.TextField(default='pending', verbose_name='state'),
        ),
    ]
