# Generated by Django 2.2.13 on 2020-09-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200824_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='private',
            field=models.BooleanField(default=False, verbose_name='private'),
        ),
    ]
