# Generated by Django 2.2.13 on 2020-09-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20200925_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='invalid',
            field=models.BooleanField(default=False, verbose_name='invalid_data'),
        ),
    ]
