# Generated by Django 2.2.13 on 2020-11-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20200925_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='prolific_id',
            field=models.TextField(default='', null=True, verbose_name='prolific_id'),
        ),
        migrations.AlterField(
            model_name='users',
            name='invalid',
            field=models.CharField(default=False, max_length=20, verbose_name='invalid_data'),
        ),
    ]
