# Generated by Django 2.2.12 on 2020-06-30 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_picture_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='recorded_at')),
                ('followers', models.BigIntegerField(null=True, verbose_name='followers')),
                ('following', models.BigIntegerField(null=True, verbose_name='following')),
                ('instagram', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
